package com.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TOP_DEALS".
 */
public class TopDeals {

    private String id;
    private String title;
    private String fpd_flag;
    private String off_percent;
    private String current_price;
    private String original_price;
    private String image;
    private String comments_count;
    private String all_posts_count;
    private String created_at;
    private String score;
    private String vote_value;
    private String state;
    private String description;
    private String share_url;
    private String deal_url;

    public TopDeals() {
    }

    public TopDeals(String id) {
        this.id = id;
    }

    public TopDeals(String id, String title, String fpd_flag, String off_percent, String current_price, String original_price, String image, String comments_count, String all_posts_count, String created_at, String score, String vote_value, String state, String description, String share_url, String deal_url) {
        this.id = id;
        this.title = title;
        this.fpd_flag = fpd_flag;
        this.off_percent = off_percent;
        this.current_price = current_price;
        this.original_price = original_price;
        this.image = image;
        this.comments_count = comments_count;
        this.all_posts_count = all_posts_count;
        this.created_at = created_at;
        this.score = score;
        this.vote_value = vote_value;
        this.state = state;
        this.description = description;
        this.share_url = share_url;
        this.deal_url = deal_url;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFpd_flag() {
        return fpd_flag;
    }

    public void setFpd_flag(String fpd_flag) {
        this.fpd_flag = fpd_flag;
    }

    public String getOff_percent() {
        return off_percent;
    }

    public void setOff_percent(String off_percent) {
        this.off_percent = off_percent;
    }

    public String getCurrent_price() {
        return current_price;
    }

    public void setCurrent_price(String current_price) {
        this.current_price = current_price;
    }

    public String getOriginal_price() {
        return original_price;
    }

    public void setOriginal_price(String original_price) {
        this.original_price = original_price;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getComments_count() {
        return comments_count;
    }

    public void setComments_count(String comments_count) {
        this.comments_count = comments_count;
    }

    public String getAll_posts_count() {
        return all_posts_count;
    }

    public void setAll_posts_count(String all_posts_count) {
        this.all_posts_count = all_posts_count;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }

    public String getVote_value() {
        return vote_value;
    }

    public void setVote_value(String vote_value) {
        this.vote_value = vote_value;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getShare_url() {
        return share_url;
    }

    public void setShare_url(String share_url) {
        this.share_url = share_url;
    }

    public String getDeal_url() {
        return deal_url;
    }

    public void setDeal_url(String deal_url) {
        this.deal_url = deal_url;
    }

}
